/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_admin (void);
GtkWidget* create_adherent (void);
GtkWidget* create_medecin (void);
GtkWidget* create_coach (void);
GtkWidget* create_dieteticien (void);
GtkWidget* create_ajoutadherent (void);
GtkWidget* create_ajoutmed (void);
GtkWidget* create_ajoutdiete (void);
GtkWidget* create_ajoutcach (void);
GtkWidget* create_affadhtree (void);
GtkWidget* create_modifieradh (void);
GtkWidget* create_modifiermed (void);
GtkWidget* create_modifierdiete (void);
GtkWidget* create_modifiercoach (void);
GtkWidget* create_supprimeradh (void);
GtkWidget* create_supprimermed (void);
GtkWidget* create_supprimerdiete (void);
GtkWidget* create_supprimercoach (void);
GtkWidget* create_medtree (void);
GtkWidget* create_diettree (void);
GtkWidget* create_coachtree (void);
GtkWidget* create_kine (void);
GtkWidget* create_ajouterkine (void);
GtkWidget* create_modifierkine (void);
GtkWidget* create_supprimerkine (void);
GtkWidget* create_treekine (void);
GtkWidget* create_ajoutgeration (void);
GtkWidget* create_geration (void);
GtkWidget* create_afftreegest (void);
GtkWidget* create_modgest (void);
GtkWidget* create_supgest (void);
GtkWidget* create_mygym (void);
GtkWidget* create_acceuil (void);
GtkWidget* create_espacecoach (void);
