/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *admin;
  GtkWidget *adherent;
  GtkWidget *medecin;
  GtkWidget *coach;
  GtkWidget *dieteticien;
  GtkWidget *ajoutadherent;
  GtkWidget *mygym;
  //GtkWidget *afficheradherent;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
   
  /*admin = create_admin ();
  gtk_widget_show (admin);*/
  mygym = create_mygym ();
  gtk_widget_show (mygym);
  adherent = create_adherent ();
  //gtk_widget_show (adherent);
  medecin = create_medecin ();
  //gtk_widget_show (medecin);
  coach = create_coach ();
  //gtk_widget_show (coach);
  dieteticien = create_dieteticien ();
  //gtk_widget_show (dieteticien);
  ajoutadherent = create_ajoutadherent ();
  //gtk_widget_show (ajoutadherent);
  //afficheradherent = create_afficheradherent ();
  //gtk_widget_show (afficheradherent);

  gtk_main ();
  return 0;
}

