/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_Admin (void);
GtkWidget* create_medecin (void);
GtkWidget* create_Dispo (void);
GtkWidget* create_Fiche (void);
GtkWidget* create_Listee (void);
GtkWidget* create_Ajoutdisp (void);
GtkWidget* create_Suppression (void);
GtkWidget* create_modif (void);
GtkWidget* create_suppr (void);
